{
 "title": "Banestes Plataforma Externa",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase='Running', namespace='sistemas-externos', pod!~'.*deploy|.*build'})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"sistemas-externos\", pod!~'.*deploy|.*build', container!=\"\", image!=\"\"}) ",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "yaxes": [
    { "format": "cpu" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"sistemas-externos\", pod!~'.*deploy|.*build', cluster=\"\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase='Running', namespace='sistemas-externos', pod!~'.*deploy|.*build'})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"sistemas-externos\", pod!~'.*deploy|.*build', container!=\"\", image!=\"\"}) ",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"sistemas-externos\", pod!~'.*deploy|.*build', cluster=\"\"})",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}