{
 "title": "Banestes V2",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Kafka LAG",
   "type": "graph",
   "description": "Kafka LAG from topic 'transacoes' and consumergroup 'geradorBoletos'",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=~\"geradorBoleto-v2\",topic=~\"transacoes\", namespace=~\"my-kafka\"})"
    }
   ]
  },
  {
   "title": "Kafka LAG",
   "type": "stat",
   "description": "Kafka LAG from topic 'transacoes' and consumergroup 'geradorBoletos'",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=~\"geradorBoleto-v2\",topic=~\"transacoes\", namespace=~\"my-kafka\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"sistemas-internos-v2\", pod!~'.*deploy|.*build', container!=\"\", image!=\"\"}) ",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Leitor Banco",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase='Running', namespace='sistemas-internos-v2', pod!~'.*deploy|.*build', pod=~'leitor-banco.*'})"
    }
   ]
  },
  {
   "title": "Leitor Arquivo",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase='Running', namespace='sistemas-internos-v2', pod!~'.*deploy|.*build', pod=~'leitor-arquivo.*'})"
    }
   ]
  },
  {
   "title": "Buscador Arquivos",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase='Running', namespace='sistemas-internos-v2', pod!~'.*deploy|.*build', pod=~'buscador-arquivos.*'})"
    }
   ]
  },
  {
   "title": "Total Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase='Running', namespace='sistemas-internos-v2', pod!~'.*deploy|.*build'})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"sistemas-internos-v2\", pod!~'.*deploy|.*build', cluster=\"\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Kafka Reader",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase='Running', namespace='sistemas-internos-v2', pod!~'.*deploy|.*build', pod=~'kafka-reader.*'})"
    }
   ]
  }
 ]
}