apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: sistemas-internos-v2
spec:
  pollingInterval: 10  # Optional. Default: 30 seconds
  cooldownPeriod:  30 # Optional. Default: 300 seconds
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-reader-banestes
  triggers:
  - type: kafka 
    metadata:
      topic: transacoes
      bootstrapServers: my-cluster-kafka-brokers.my-kafka.svc.cluster.local:9092
      consumerGroup: geradorBoleto-v2
      lagThreshold: '10' 
      offsetResetPolicy: 'latest' 
      version: 1.0.0 
      #partitionLimitation: '1,2,10-20,31' 